sudo: required
services:
  - docker

before_install:
  - gem install bundler --pre
  - docker build -t mydocker/docker-react -f Dockerfile.dev .

script:
  - docker run mydocker/docker-react npm run test -- --coverage
